# Generated by Django 5.2.8 on 2025-11-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='user',
            new_name='uploader',
        ),
    ]
