# Generated by Django 5.2.8 on 2025-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_userfile_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size', models.PositiveIntegerField(default=10485760, help_text='Maximum allowed file size in bytes')),
                ('allowed_file_types', models.CharField(default='*', help_text="Comma-separated list of allowed file extensions. Use '*' for all.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
