# Generated by Django 5.2.8 on 2025-11-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_appsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'App Settings', 'verbose_name_plural': 'App Settings'},
        ),
        migrations.AlterModelOptions(
            name='userfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'User File', 'verbose_name_plural': 'User Files'},
        ),
        migrations.AddField(
            model_name='userfile',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Calculated expiration date/time', null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='expiry_option',
            field=models.CharField(choices=[('1_day', '1 Day'), ('3_days', '3 Days'), ('7_days', '7 Days'), ('30_days', '30 Days'), ('never', 'Never Expire')], default='never', help_text='Select when this file should expire', max_length=10),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='max_file_size',
            field=models.PositiveIntegerField(default=1048576, help_text='Maximum allowed file size in bytes'),
        ),
    ]
