# Generated by Django 5.2.8 on 2025-11-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_appsettings_options_alter_userfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfile',
            name='expiry_option',
        ),
        migrations.AddField(
            model_name='userfile',
            name='expiry_days',
            field=models.PositiveIntegerField(default=0, help_text='Days until expiry'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='expiry_hours',
            field=models.PositiveIntegerField(default=0, help_text='Hours until expiry'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='expiry_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes until expiry'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='expiry_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Seconds until expiry'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='never_expire',
            field=models.BooleanField(default=True, help_text='File never expires'),
        ),
    ]
